/**
 * Typed access to the world-map layout (`worldmap.json`) — the schematic the
 * pause menu's MAP screen draws. The JSON is GENERATED by
 * `tools/maps/world_layout.py` (which also verifies the layout against the
 * shipped warp geometry) — edit the NODES/ROADS tables there and re-run it,
 * never this file's data by hand.
 */
import layoutJson from './worldmap.json';

export type WorldMapNodeKind = 'town' | 'route' | 'dungeon' | 'hub' | 'landmark';
export type WorldMapRoadKind = 'road' | 'lane' | 'gate' | 'pass';

export interface WorldMapNode {
  id: string; // the node's anchor map id
  /** Centre position in the layout's 220x140 virtual box (x right, y down). */
  x: number;
  y: number;
  kind: WorldMapNodeKind;
  region: string;
  name: string;
}

export interface WorldMapRoad {
  a: string;
  b: string;
  kind: WorldMapRoadKind;
}

export interface WorldMapLayout {
  nodes: WorldMapNode[];
  roads: WorldMapRoad[];
  /** EVERY map id -> the node it belongs to (interiors -> their town,
   *  dungeon floors -> the mouth, annex scars -> their host). */
  members: Record<string, string>;
}

/** The layout's virtual-box size the node coordinates live in. */
export const WORLD_MAP_BOX = { width: 220, height: 140 } as const;

export const WORLD_MAP: WorldMapLayout = layoutJson as WorldMapLayout;

const NODE_BY_ID = new Map(WORLD_MAP.nodes.map((n) => [n.id, n]));

export function worldMapNode(id: string): WorldMapNode | undefined {
  return NODE_BY_ID.get(id);
}

/** The map-screen node the given map id belongs to (undefined off-atlas). */
export function worldMapNodeForMap(mapId: string): WorldMapNode | undefined {
  const anchor = WORLD_MAP.members[mapId];
  return anchor ? NODE_BY_ID.get(anchor) : undefined;
}
